---

# ----------------------------------------------------------
#                ALL VM
# ----------------------------------------------------------
- name: Install docker
  hosts: all:!jdac
  become: true
  tags:
    - run-app-

  pre_tasks:
    - name: Install epel-release
      yum:
        name: epel-release
        state: latest

    - name: install the 'Development tools' package group
      yum:
        name: "@Development tools"
        state: present

    - name: Python-devel
      yum:
        name: python-devel
        state: present

    - name: Install python pip
      yum:
        name: python-pip
        state: latest

    - name: Install docker
      pip:
        name: docker

  tasks:
    - include_role:
        name: docker-setup-role

# ----------------------------------------------------------------
#                REPOSITORY VM - RUN REPOSITORY GOS AND POSTGRES
# ---------------------------------------------------------------
- name: Deploy Gos, private github repository
  hosts: repository
  become: true
  tags:
    - deploy-repository

  pre_tasks:
    - name: Install git
      yum:
        name: git
        state: present
        update_cache: yes

  tasks:
    - include_role:
        name: postgres-setup-role
      vars:
        docker_postgres__name: 4dvop-pg-ctn
        docker_postgres__image: postgres:11.1-alpine
        docker_postgres__port: 5678
        docker_postgres__superuser_name: superuser
        docker_postgres__superuser_password: supersecret
        docker_postgres__env:
          POSTGRES_DB: 4dvop-db
        docker_postgres__log_driver: syslog
        docker_postgres__log_options:
          syslog-facility: local0
          tag: "{{ docker_postgres__name }}"

    - name: Deploy private repository (gogs) task
      docker_container:
        name: gogs-ctn
        image: gogs/gogs
        state: started
        ports:
          - "23:22"
          - "4000:3000"
        networks:
        - name: app-network
        networks_cli_compatible: yes


# ----------------------------------------------------------
#                REGISTRY VM
# ----------------------------------------------------------
- name: Deploy registry, private docker registry
  hosts: registry
  become: true
  tags:
    - deploy-registry

  tasks:
    - name: Deploy private registry task
      docker_container:
        name: registry-ctn
        image: registry
        state: started
        ports:
          - "8000:5000"

    - name: Deploy docker registry frontend task
      docker_container:
        name: registry-frontend-ctn
        state: started
        image: konradkleine/docker-registry-frontend:v2
        # run jdac with 8080 and change this to 80
        ports:
          - "8080:80"
        env:
          ENV_DOCKER_REGISTRY_HOST: registry-ctn
          ENV_DOCKER_REGISTRY_PORT: "5000"
          FRONTEND_BROWSE_ONLY_MODE: "false"

    - name: Create a registry-network network and connect containers
      docker_network:
        name: registry-network
        connected:
          - registry-ctn
          - registry-frontend-ctn


# --------------------------------------------------------------------------
# SETUP docker registry security settings for pushing images - DEPLOY VM
# --------------------------------------------------------------------------
#- name:  Setup daemon registry security setting for pushing images
#  hosts: deploy
#  become: true
#  tags:
#    - registry-daemon
#
#  tasks:
#    - name: Copy daemon json file to  deploy vm task
#      copy:
#        src: /opt/bitnami/jenkins/jenkins_home/workspace/4dvop-project_complete-playbook/appli/daemon.json
#        dest: /etc/docker/daemon.json
#
#    - name: restart docker
#      shell: service docker restart

# ----------------------------------------------------------
#                LOCAL build AND PUSH TO REGISTRY images VM
# ----------------------------------------------------------

- name:  Install requirements, Build api and studentlist and push to registry
  hosts: jdac
  become: true
  tags:
    - build-simple-api-and-website

  pre_tasks:
    - name: install Docker compose task in local
      pip:
        name: docker
        state: present

    - name: Docker-compose installation task in local
      pip:
        name: docker-compose
        state: present

  tasks:
    - name: Build docker compose yaml file task
      docker_compose:
        project_src: /opt/bitnami/jenkins/jenkins_home/workspace/4dvop-project_complete-playbook/appli/simple_api/simple_api
        build: yes
      register: output
# ----------------------------------------------------------
#      RUN app on Build system
# ----------------------------------------------------------

#- name:  Run simple api and studentlist app
#  hosts: jdac
#  become: true
#  tags:
#    - run-simple-api-and-website
#  tasks:
#    - name: Push api to docker private registry task
#      docker_image:
#        name: 172.16.203.147:8000/simple-api
#        tag: v1
#        push: yes
#        source: local
#
#    - name: Tag php apache app image and push to registry task
#      docker_image:
#        name: php:apache
#        repository: 172.16.203.147:8000/php:apache
#        force_tag: yes
#        push: yes
#        source: local

# ----------------------------------------------------------
#                RUN SIMPLE API - BUILD SYSTEM
# ----------------------------------------------------------
- name:  Run simple api
  hosts: jdac
  become: true
  tags:
    - run-simple-api

  tasks:
    - name: Run simple api from build system task
      docker_container:
        name: simple-api
        image: 172.16.203.147:8000/simple-api:v1
        ports:
          - "5001:5000"


# ----------------------------------------------------------
#      TEST simple api and stop container - VM DEPLOY
# ----------------------------------------------------------
- name:  curl check
  hosts: deploy
  tags:
    - test-simple-api
  tasks:
    - name: Run check api
      shell:
        cmd: curl -u toto:python -X GET http://localhost:5001/pozos/api/v1.0/get_student_ages

    - name: delete api container
      docker_container:
        name: simple-api
        state: absent

# ----------------------------------------------------------
#                CLAIR SCAN Build
# ----------------------------------------------------------
- name:  Clair Scan - Security testing
  hosts: jdac
  tags:
    - clair
  tasks:
    - name: Run clair task
      docker_compose:
        project_src: /opt/bitnami/jenkins/jenkins_home/workspace/4dvop_master/deploy/clair
        build: yes
      register: output

    - name: Run clair job
      shell:
        cmd: clair-scanner --clair="http://clair:6060" --ip jdac simple-api:latest


#    - name: Run php apache from private registry task
#      docker_container:
#        name: app-ctn
#        image: 172.16.203.147:8000/php:apache
#        ports:
#          - "3000:80"
#
#    - name: Create and connect api and app containers
#      docker_network:
#        name: app-network
#        connected:
#          - api-ctn
#          - app-ctn
