---

# ----------------------------------------------------------
#                ALL VM
# ----------------------------------------------------------
- name: Install docker
  hosts: all
  become: true
  
  pre_tasks:
    - name: Install epel-release
      yum:
        name: epel-release
        state: latest
    - name: Install python pip
      yum:
        name: python-pip
        state: latest
    - name: Install docker-py
      pip:
        name: docker-py

  tasks:
    - include_role: 
        name: geerlingguy.docker


# --------------------------------------------------------------
#                REPOSITORY  VM - SETUP postgres for gogs image
# --------------------------------------------------------------

- name: setup postgres
  hosts: repository
  become: true

  tasks:
    - include_role: 
        name: levonet.docker_postgres
      vars:
        docker_postgres__name: 4dvop-pg-ctn
        docker_postgres__image: postgres:11.1-alpine
        docker_postgres__port: 5678
        docker_postgres__superuser_name: superuser
        docker_postgres__superuser_password: supersecret
        docker_postgres__env:
          POSTGRES_DB: 4dvop-db
        docker_postgres__log_driver: syslog
        docker_postgres__log_options:
          syslog-facility: local0
          tag: "{{ docker_postgres__name }}"

# ----------------------------------------------------------
#                REPOSITORY  VM
# ---------------------------------------------------------- 
- name: Install git
  hosts: repository
  become: true

  tasks:
    - name: Install git
      yum:
        name: git
        state: present
        update_cache: yes

# ----------------------------------------------------------
#                REPOSITORY VM
# ----------------------------------------------------------
- name: Deploy Gos, private github repository
  hosts: repository
  become: true

  tasks:
    - name: Deploy private repository task
      docker_container:
        name: gogs-ctn
        image: gogs/gogs
        state: started
        ports:
          - "23:22"
          - "4000:3000"
        networks:
        - name: app-network
        networks_cli_compatible: yes


# ----------------------------------------------------------
#                REGISTRY VM
# ----------------------------------------------------------
- name: Deploy registry, private docker registry
  hosts: registry
  become: true
  
  tasks:
    - name: Deploy private repository task
      docker_container:
        name: registry-ctn
        image: registry
        state: started
        ports:
          - "8000:5000"
          
- name: Deploy registry frontend
  hosts: registry
  become: true
  
  tasks:
    - name: Deploy registry fronetnd task
      docker_container:
        name: registry-frontend
        state: started
        image: konradkleine/docker-registry-frontend:v2
        links: registry-ctn:registry-ctn
        ports:
          - "80:80"
        env:
          ENV_DOCKER_REGISTRY_HOST: registry-ctn
          ENV_DOCKER_REGISTRY_PORT: "5000"
          FRONTEND_BROWSE_ONLY_MODE: "false"

# ----------------------------------------------------------
#                APPLI - Clone repository
# ----------------------------------------------------------
- name: Clone Repository
  hosts: app
  become: true
  
  tasks:
    - name: clone
      copy:
        src: /opt/bitnami/jenkins/jenkins_home/workspace/4dvop_master/appli
        dest: /
        owner: root
        group: root
        mode: "0777"


# ----------------------------------------------------------
#                LOCAL build images VM
# ----------------------------------------------------------
- name:  Build and push api and studentlist app
  hosts: app
  tags:
    - build-push-image
  tasks:
    - name: Build an image and push it to a private repo
      docker_image:
        build:
          path: /simple_api/
        name: 192.168.18.12:8000/simple-api
        tag: v1
        push: yes
        source: build
    
    - name: Pull from registry
      docker_image:
        name: php:apache
        build.pull: yes
        source: pull