---

# ----------------------------------------------------------
#     Install prerequisites on Registry and Repository
# ----------------------------------------------------------
#- name: Install docker
#  hosts: registry,repository
#  become: true
#  tags:
#    - inst-prerequisites

#  tasks:
#    - name: Install epel-release
#      yum:
#        name: epel-release
#        state: latest
      
#    - name: Install python pip
#      yum:
#        name: python-pip
#        state: latest
    
#    - name: Install docker
#      pip:
#        name: docker
  
#    - include_role: 
#        name: geerlingguy.docker

# ----------------------------------------------------------
#      Install prerequisites on Application and Deploy
# ----------------------------------------------------------

- name: Install docker on app server
  hosts: all
  become: true
  tags:
    - inst-prerequisites

  tasks:
    - name: Install epel-release-app
      yum:
        name: epel-release
        state: latest
      
    - name: install the 'Development tools' package group
      yum:
        name: "@Development tools"
        state: present

    - name: Python-devel
      yum:
        name: python-devel
        state: present

    - name: Upgrade pip
      pip:
        name: pip
        executable: pip2
        extra_args: --upgrade

    - name: Install docker
      pip:
        name: docker
    
    - name: Install docker-compose
      pip:
        name: docker-compose



# ----------------------------------------------------------
#     RUN REPOSITORY GOS AND POSTGRES
# ----------------------------------------------------------
- name: Deploy Gos, private github repository
  hosts: repository
  become: true
  tags:
    - deploy-repository
  
  pre_tasks:
    - name: Install git
      yum:
        name: git
        state: present
        update_cache: yes
    
  tasks:

    - include_role: 
        name: postgres-setup-role
      vars:
        docker_postgres__name: 4dvop-pg-ctn
        docker_postgres__image: postgres:11.1-alpine
        docker_postgres__port: 5678
        docker_postgres__superuser_name: superuser
        docker_postgres__superuser_password: supersecret
        docker_postgres__env:
          POSTGRES_DB: 4dvop-db
        docker_postgres__log_driver: syslog
        docker_postgres__log_options:
          syslog-facility: local0
          tag: "{{ docker_postgres__name }}"

    - name: Deploy private repository task
      docker_container:
        name: gogs-ctn
        image: gogs/gogs
        state: started
        ports:
          - "4000:3000"
        networks:
        - name: app-network
        networks_cli_compatible: yes

  

# ----------------------------------------------------------
#    RUN REGISTRY VM
# ----------------------------------------------------------
- name: Deploy registry, private docker registry
  hosts: registry
  become: true
  tags:
    - deploy-registry  
  tasks:
    - name: Deploy private repository task
      docker_container:
        name: registry-ctn
        image: registry
        state: started
        ports:
          - "8000:5000"
          
    - name: Deploy registry frontend task
      docker_container:
        name: registry-frontend
        state: started
        image: konradkleine/docker-registry-frontend:v2
        links: registry-ctn:registry-ctn
        ports:
          - "80:80"
        env:
          ENV_DOCKER_REGISTRY_HOST: registry-ctn
          ENV_DOCKER_REGISTRY_PORT: "5000"
          FRONTEND_BROWSE_ONLY_MODE: "false"

    - name: Create a registry-network network and connect containers
      docker_network:
        name: registry-network
        connected:
          - registry-ctn
          - registry-frontend

# ----------------------------------------------------------
#    GET Code From Repository on Deploy
# ----------------------------------------------------------
#- name:  Get code
#  hosts: deploy
#  tags:
#    - get-code
#  tasks:
#    - name: Get code from private repo
#      git:
#         repo: 'http://192.168.48.11:4000/Djodane/4dvop'
#         dest: /app
#         clone: yes

# ----------------------------------------------------------
#    GET Code From Repository on appli
# ----------------------------------------------------------
#- name:  Get code
#  hosts: app
#  tags:
#    - get-code
#  tasks:
#    - name: Get code from private repo
#      git:
#         repo: 'http://192.168.48.11:4000/Djodane/4dvop'
#         dest: /app
#         clone: yes

# ----------------------------------------------------------
#    BUILD images on jdac and push to Registry
# ----------------------------------------------------------
- name:  Build and push api and studentlist app
  hosts: jdac
  tags:
    - build-simple-api
  tasks:
    - name: Build app and push it to a private repo
      docker_image:
        build:
          path: /opt/bitnami/jenkins/jenkins_home/workspace/4dvop_master/appli/simple_api
        name: 192.168.48.12:8000/simple-api
        tag: latest
        push: yes
        source: build

# ----------------------------------------------------------
#      RUN app on Deploy for test api
# ----------------------------------------------------------

- name:  Run app
  hosts: jdac
  tags:
    - run-simple-api
  tasks:
    - name: Run app task
      docker_container:
        name: simple-api
        image: simple-api:latest
        ports:
          - "5001:5000"
#        volumes:
#          - /opt/bitnami/jenkins/jenkins_home/workspace/4dvop_master/appli/simple_api:/usr/src/app
#          - /app/appli/simple_api/student_age.json:/data/student_age.json

# ----------------------------------------------------------
#      TEST api from Deploy
# ---------------------------------------------------------- 
- name:  curl check
  hosts: deploy
  tags:
    - test-simple-api
  tasks:
    - name: Run check api
      shell: 
        cmd: curl -u toto:python -X GET http://jdac:5001/pozos/api/v1.0/get_student_ages

# ----------------------------------------------------------
#      STOP api container from Deploy
# ---------------------------------------------------------- 

- name: Stop simple api container
  hosts: deploy
  tags:
    - test-simple-api
  tasks:
     - name: Stop api
       docker_container:
         name: simple-api
         state: stopped



# ----------------------------------------------------------
#                CLAIR SCAN Build
# ----------------------------------------------------------
- name:  Clair Scan
  hosts: jdac
  tags:
    - clair
  tasks:
    - name: Run clair task
      docker_compose:
        project_src: /opt/bitnami/jenkins/jenkins_home/workspace/4dvop_master/deploy/clair
        build: yes
      register: output


# ----------------------------------------------------------
#                CLAIR SCAN Launch
# ----------------------------------------------------------
- name:  Clair launch
  hosts: jdac
  tags:
    - clair
  tasks:
    - name: Run clair job
      shell:
        cmd: clair-scanner --clair="http://clair:6060" --ip jdac simple-api:latest


#### Add push simple-api

# ----------------------------------------------------------
#     CLEAN Deploy docker image simple-api
# ----------------------------------------------------------
### A faire apres clair # Penser a ajouter la step dans le jenkinsfile
- name:  Clean images
  hosts: jdac
  tags:
    - clean-api-image
  tasks:
    - name: Clean images
      docker_image:
        name: 192.168.48.12:8000/simple-api
        state: absent



# ----------------------------------------------------------
#                APPLI Add daemon.json
# ----------------------------------------------------------
- name: Clone Repository
  hosts: deploy
  become: true
  tags:
    - run-app
    
  tasks:
 #   - name: move app
 #     copy:
 #       src: /opt/bitnami/jenkins/jenkins_home/workspace/4dvop_master/appli
 #       dest: /home/centos

#    - name: copy daemon.json
#      shell:
#        cmd: cp /app/appli/daemon.json /etc/docker/daemon.json  
    - name: copy daemon.json
      copy:
        src: /opt/bitnami/jenkins/jenkins_home/workspace/4dvop_master/appli/daemon.json
        dst: /etc/docker/daemon.json   

    - name: restart docker
      shell: service docker restart


# ----------------------------------------------------------
#                DEPLOY app on App
# ----------------------------------------------------------
#- name:  Get Image 
#  hosts: app
#  tags:
#    - run-app
#  tasks:    
#    - name: Pull image
#      docker_image:
#        name: php:apache
#        source: pull

# ----------------------------------------------------------
#                RUN app on App
# ----------------------------------------------------------
- name:  Run app
  hosts: app
  tags:
    - run-app
  tasks:
    - name: Run app task
      docker_compose:
        project_src: /opt/bitnami/jenkins/jenkins_home/workspace/4dvop_master/appli
        build: no
      register: output

# ----------------------------------------------------------
#                E2E Security tests with Gaultl/Arachni
# ----------------------------------------------------------

- name:  Get gaultl code
  hosts: jdac
  tags:
    - e2e-test
  tasks:
    - name: Get code from gauntlt-docker
      git:
         repo: 'https://github.com/gauntlt/gauntlt-docker'
         dest: /gauntlt
         clone: yes

    - name: Run gaultlt container
      shell: make build
      args:
        chdir: /gauntlt

    - name: Add binary stub to path
      shell: install-stub
      args:
        chdir: /gauntlt