---

# ----------------------------------------------------------
#                APP VM
# ----------------------------------------------------------
- name: Install docker
  hosts: app
  become: true

  tasks:
    - include_role: 
        name: geerlingguy.docker

# ----------------------------------------------------------
#                DEPLOY VM
# ----------------------------------------------------------
#- name: deploy Jenkkins Docker Ansible Clair
  #hosts: deploy
  #become: true

  #tasks:
   # - name: Deploy jenkins-docker-ansible-clair task
    #  docker_container:
     #   hostname: jdac
      #  name: jenkins-docker-ansible-clair
       # image: dirane/jenkins-docker-ansible-clair
        #state: started
        #ports:
         # - "8080:80"
          #- "5000:5000"
          #- "443:8443"

# ----------------------------------------------------------
#                REPOSITORY VM
# ----------------------------------------------------------
- name: Deploy Gos, private github repository
  hosts: repository
  become: true
  
  tasks:
    - name: Deploy private repository task
      docker_container:
        hostname: gogs-ctn
        name: gogs/gogs
        state: started
        ports:
          - "22:22"
          - "4000:3000"

# ----------------------------------------------------------
#                REGISTRY VM
# ----------------------------------------------------------
- name: Deploy Gos, private github repository
  hosts: repository
  gather_facts: no
  become: true
  
  tasks:
    - name: Deploy private repository task
      docker_container:
        hostname: registry-ctn
        name: registry
        state: started
        ports:
          - "8000:5000"