---

# ----------------------------------------------------------
#                ALL VM
# ----------------------------------------------------------
- name: Install docker
  hosts: all
  become: true
  
  pre_tasks:
    - name: Install epel-release
      yum:
        name: epel-release
        state: latest
    - name: Install python pip
      yum:
        name: python-pip
        state: latest
    - name: Install docker-py
      pip:
        name: docker-py

  tasks:
    - include_role: 
        name: geerlingguy.docker

# ----------------------------------------------------------
#                REPOSITORY && LOCALHOST VM
# ---------------------------------------------------------- 
- name: Install git
  hosts: repository
  become: true

  tasks:
    - name: Install git
      yum:
        name: git
        state: present
        update_cache: yes

# ----------------------------------------------------------
#                REPOSITORY VM
# ----------------------------------------------------------
- name: Deploy Gos, private github repository
  hosts: repository
  become: true

  tasks:
    - name: Deploy private repository task
      docker_container:
        name: gogs-ctn
        image: gogs/gogs
        state: started
        ports:
          - "23:22"
          - "4000:3000"
        networks:
        - name: app-network


# ----------------------------------------------------------
#                REGISTRY VM
# ----------------------------------------------------------
- name: Deploy registry, private docker registry
  hosts: registry
  become: true
  
  tasks:
    - name: Deploy private repository task
      docker_container:
        name: registry-ctn
        image: registry
        state: started
        ports:
          - "8000:5000"

# ----------------------------------------------------------
#                APP VM
# ----------------------------------------------------------