version: '3'

services:
  api:
    build: ./simple_api
    volumes:
      - ./simple_api:/usr/src/app
      - /home/salah/Desktop/student-list/simple_api/student_age.json:/data/student_age.json
    ports:
      - 5001:80

  website:
    image: php:apache
    volumes:
      - ./website:/var/www/html
    ports:
      - 3000:80
    depends_on:
      - api

