version: '3'

services:
  api:
    build: .
    container_name: api
    image: 192.168.1.37:8000/simple-api:v1
    volumes:
      - "./student_age.json:/data/student_age.json"
    ports:
      - 5001:5000

  website:
    image: php:apache
    container_name: app
    volumes:
      - "./website:/var/www/html"
    ports:
      - 3000:80
    depends_on:
      - api

