version: '3'

services:
  api:
    build: /opt/bitnami/jenkins/jenkins_home/workspace/4dvop-project_complete-playbook/appli/simple_api/simple_api
    container_name: api
    image: 172.16.203.147:8000/simple-api:v1
    ports:
      - 5001:5000

  website:
    image: php:apache
    container_name: app
    volumes:
      - ./website:/var/www/html
    ports:
      - 3000:80
    depends_on:
      - api

