version: '3'

services:
  api:
    build: ./simple_api
    container_name: api
    image: simple-api
    volumes:
      - ./simple_api:/usr/src/app
      - ./simple_api/student_age.json:/data/student_age.json
    ports:
      - 5001:5000

  website:
    image: php:apache
    container_name: app
    volumes:
      - ./website:/var/www/html
    ports:
      - 3000:80
    depends_on:
      - api

