version: '3'

services:
  clair-db:
    image: arminc/clair-scanner
    container_name: clair-db

  clair:
    image: arminc/clair-local-scan
    container_name: clair
    ports:
          - "6060:6060"
    links:
      clair-db:clair-db

