version: '3'

services:
  api:
    build: /opt/bitnami/jenkins/jenkins_home/workspace/4DVOP-PROJECT_master/appli/simple_api
    container_name: api
    image: 192.168.1.122:8000/simple-api:v1
    ports:
      - 5002:5000

  website:
    image: php:apache
    container_name: app
    volumes:
      - "/opt/bitnami/jenkins/jenkins_home/workspace/4DVOP-PROJECT_master/appli/website:/var/www/html"
    environment:
      - USERNAME=toto
      - PASSWORD=python
    ports:
      - 3000:80
    depends_on:
      - api

