version: '3'

services:
  api:
    container_name: api
    image: 192.168.48.12:8000/simple-api:v1
    ports:
      - 5001:5000

  website:
    image: php:apache
    container_name: app
    volumes:
      - "/home/centos/website/index.php:/var/www/html/index.php"
    environment:
      - USERNAME=toto
      - PASSWORD=python
    ports:
      - 3000:80
    depends_on:
      - api
