version: '3'

services:
  api:
    container_name: api
    image: 172.16.203.147:8000/simple-api:latest
    ports:
      - 5000:5000

  website:
    image: 172.16.203.147:8000/php:apache
    container_name: app
    ports:
      - 80:80
    depends_on:
      - api

